#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Playbook for configuring ntp server settings

- include_vars: "../../osconfig-common/vars/{{ ansible_os_family | lower }}.yml"

- name: osconfig-ntp-server | configure | Verify ntp servers are accessible
  become: yes
  command: /usr/sbin/ntpdate -q {{ ntp_servers | join(' ') }}
  when: not (ardana_notify_osconfig_ntp_restart_required is not defined)
        and ardana_notify_osconfig_ntp_restart_required.changed and
        ntp_restarted is not defined
  register: ntpdate_result
  until: ntpdate_result | success
  retries: 120
  delay: 2

- name: osconfig-ntp-server | configure | Record ntp server responses
  debug:
    var: ntpdate_result.stdout_lines
  when: ntpdate_result | success

- name: osconfig-ntp-server | configure | Stop ntp so time can be updated
  become: yes
  service:
    name={{ ntp_service_name }}
    state=stopped
  when: not (ardana_notify_osconfig_ntp_restart_required is not defined)
        and ardana_notify_osconfig_ntp_restart_required.changed and
        ntp_restarted is not defined
